2023-04-27 11:52:12,880 : INFO : root : Loading config.
2023-04-27 11:52:13,160 : INFO : ConfigProcessor : Config spec file cache created: C:\Users\dorus\AppData\Local\Temp\config_spec.mpf_cache
2023-04-27 11:52:13,160 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-04-27 11:52:13,160 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\mpfconfig.yaml.
2023-04-27 11:52:13,220 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\mpfconfig.yaml
2023-04-27 11:52:13,220 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\config\config.yaml.
2023-04-27 11:52:13,234 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\config\config.yaml
2023-04-27 11:52:13,236 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\746ec81b4daa2d0da75c83d96aab4d3b.mpf_cache
2023-04-27 11:52:13,332 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2023-04-27 11:52:13,343 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\modes\attract\config\attract.yaml
2023-04-27 11:52:13,343 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\modes\attract\config\attract.yaml.
2023-04-27 11:52:13,365 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\modes\attract\config\attract.yaml
2023-04-27 11:52:13,366 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\8a0bfa659085c557a87bd7bffffc57e9.mpf_cache
2023-04-27 11:52:13,366 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\modes\game\config\game.yaml.
2023-04-27 11:52:13,376 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\modes\game\config\game.yaml
2023-04-27 11:52:13,377 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\2af2fbde21c8ccb06b52e16890475468.mpf_cache
2023-04-27 11:52:13,378 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\dc3f1dc568bf4a7e19421e344f596ebb.mpf_cache
2023-04-27 11:52:13,386 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\config_spec.yaml
2023-04-27 11:52:13,386 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\modes\base\config\base.yaml.
2023-04-27 11:52:13,400 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\modes\base\config\base.yaml
2023-04-27 11:52:13,401 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\dc3f1dc568bf4a7e19421e344f596ebb.mpf_cache
2023-04-27 11:52:13,403 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\2179cb7b2e2b1bfc9435f75056934701.mpf_cache
2023-04-27 11:52:13,411 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\config_spec.yaml
2023-04-27 11:52:13,411 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\modes\attract\shows\.\attract_display_loop.yaml.
2023-04-27 11:52:13,427 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest\modes\attract\shows\.\attract_display_loop.yaml
2023-04-27 11:52:13,427 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\2179cb7b2e2b1bfc9435f75056934701.mpf_cache
2023-04-27 11:52:13,428 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.0
2023-04-27 11:52:13,428 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2023-04-27-11-52-12-mpf-LAPTOP-AS8QDAQG.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-04-27 11:52:13,428 : INFO : Machine : MPF path: C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf
2023-04-27 11:52:13,428 : INFO : Machine : Machine path: C:\Users\dorus\OneDrive\Documents\Pinball\Github\Pinball-MPF\ledtest
2023-04-27 11:52:13,428 : INFO : Machine : Platform: win32
2023-04-27 11:52:13,428 : INFO : Machine : Python executable location: C:\Users\dorus\.local\pipx\venvs\mpf\Scripts\python.exe
2023-04-27 11:52:13,428 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-04-27 11:52:13,430 : INFO : Machine : Initialise MPF.
2023-04-27 11:52:13,918 : INFO : OPP : Connecting to COM10 at 115200bps
2023-04-27 11:52:14,016 : INFO : OPP : Init of OPP board 0 done
2023-04-27 11:52:14,016 : INFO : OPP : Connecting to COM11 at 115200bps
2023-04-27 11:52:14,092 : INFO : OPP : Init of OPP board 1 done
2023-04-27 11:52:14,093 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,124 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-04-27 11:52:14,124 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.0', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,124 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,124 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,153 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19044-SP0', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,153 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,153 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,153 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19044', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,153 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2023-04-27 11:52:14,153 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-04-27 11:52:14,165 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2023-04-27 11:52:14,172 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2023-04-27 11:52:14,175 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...es:" found.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...es:" found.')>)>
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py", line 744, in _queue_task_done
    future.result()
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py", line 657, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\show_controller.py", line 52, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\assets\show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_display_loop" >> Invalid section "slides:" found. Context: attract_display_loop Error Code: CFE-show-4 (https://docs.missionpinball.org/en/0.56/logs/CFE-show-4.html)
2023-04-27 11:52:14,178 : INFO : Machine : Starting the main run loop.
2023-04-27 11:52:14,182 : INFO : Machine : Shutting down...
2023-04-27 11:52:14,182 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-04-27 11:52:14,183 : ERROR : OPP : Stop called on serial connection COM11
2023-04-27 11:52:14,188 : ERROR : OPP : Stop called on serial connection COM10
2023-04-27 11:52:15,203 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py", line 744, in _queue_task_done
    future.result()
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py", line 657, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\show_controller.py", line 52, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\assets\show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "C:\Users\dorus\.local\pipx\venvs\mpf\lib\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_display_loop" >> Invalid section "slides:" found. Context: attract_display_loop Error Code: CFE-show-4 (https://docs.missionpinball.org/en/0.56/logs/CFE-show-4.html)
2023-04-27 11:52:15,206 : INFO : root : MPF run loop ended.
