2022-09-24 16:32:53,531 : INFO : root : Loading config.
2022-09-24 16:32:53,534 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-09-24 16:32:53,535 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\e58a4b50dd07e9e66a1a779c252c0c34.mpf_cache
2022-09-24 16:32:53,619 : WARNING : ConfigProcessor : Config file in cache changed: C:\pinball\Pinball-MPF\mpfv1\modes\attract\config\attract.yaml
2022-09-24 16:32:53,619 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2022-09-24 16:32:53,621 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\modes\attract\config\attract.yaml
2022-09-24 16:32:53,621 : INFO : ConfigProcessor : Loading config from file C:\pinball\Pinball-MPF\mpfv1\modes\attract\config\attract.yaml.
2022-09-24 16:32:53,636 : INFO : ConfigProcessor : Loading config: C:\pinball\Pinball-MPF\mpfv1\modes\attract\config\attract.yaml
2022-09-24 16:32:53,636 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\444cf03b543d197e203cfa23af3f8fc0.mpf_cache
2022-09-24 16:32:53,637 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\336e6d2601ccb63523c70814805acbf1.mpf_cache
2022-09-24 16:32:53,638 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\997bf01789d16ed996f231036966dd64.mpf_cache
2022-09-24 16:32:53,639 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\99703a5eb7b45595525b767565d37410.mpf_cache
2022-09-24 16:32:53,640 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\3bda3283678547d211760e16eb23b4da.mpf_cache
2022-09-24 16:32:53,640 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\9bc560b11d83fb4ed736b388b885a5d3.mpf_cache
2022-09-24 16:32:53,641 : INFO : ConfigProcessor : Loading config from file C:\pinball\Pinball-MPF\mpfv1\modes\attract\shows\.\attract_light_show.yaml.
2022-09-24 16:32:53,651 : INFO : ConfigProcessor : Loading config: C:\pinball\Pinball-MPF\mpfv1\modes\attract\shows\.\attract_light_show.yaml
2022-09-24 16:32:53,652 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\cbb93b936ab62d0ca529008175910dd1.mpf_cache
2022-09-24 16:32:53,653 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2022-09-24 16:32:53,653 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2022-09-24-16-32-53-mpf-LAPTOP-AS8QDAQG.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2022-09-24 16:32:53,654 : INFO : Machine : MPF path: C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf
2022-09-24 16:32:53,654 : INFO : Machine : Machine path: C:\pinball\Pinball-MPF\mpfv1
2022-09-24 16:32:53,654 : INFO : Machine : Platform: win32
2022-09-24 16:32:53,654 : INFO : Machine : Python executable location: C:\Users\dorus\AppData\Local\Programs\Python\Python38\python.exe
2022-09-24 16:32:53,654 : INFO : Machine : Python version: 3.8.10 (64-bit)
2022-09-24 16:32:53,656 : INFO : Machine : Initialise MPF.
2022-09-24 16:32:53,805 : INFO : OPP : Connecting to COM10 at 115200bps
2022-09-24 16:32:53,921 : INFO : OPP : Init of OPP board 0 done
2022-09-24 16:32:53,922 : INFO : OPP : Connecting to COM11 at 115200bps
2022-09-24 16:32:54,013 : INFO : OPP : Init of OPP board 1 done
2022-09-24 16:32:54,013 : INFO : OPP : Connecting to COM7 at 115200bps
2022-09-24 16:32:54,106 : INFO : OPP : Init of OPP board 2 done
2022-09-24 16:32:54,107 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,167 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2022-09-24 16:32:54,168 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 31200, 'prev_value': None, 'change': True}
2022-09-24 16:32:54,168 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,168 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,168 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.8.10', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,180 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19044-SP0', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,180 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,180 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,180 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19044', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,180 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2022-09-24 16:32:54,180 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2022-09-24 16:32:54,199 : INFO : EventManager : Event: ======'drop_target_bank_db_dropbank_up'====== Args={}
2022-09-24 16:32:54,206 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2022-09-24 16:32:54,207 : INFO : SwitchController : Found active switch: ('2-0-25', <Platform.OPP>) <switch.s_trough_jam>
2022-09-24 16:32:54,211 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2022-09-24 16:32:54,214 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2022-09-24 16:32:56,260 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2022-09-24 16:32:56,262 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2022-09-24 16:32:56,271 : INFO : ball_device.bd_trough : BCH: Count is unstable. Trying to reorder balls.
2022-09-24 16:32:56,272 : WARNING : ball_device.bd_trough : Cannot reorder device because eject_coil_reorder_pulse is not configured
2022-09-24 16:32:56,272 : INFO : ball_device.bd_trough : BCH: Repulse done. Waiting for balls to settle.
2022-09-24 16:32:56,272 : INFO : ball_device.bd_trough : BCH: Initial count: 1
2022-09-24 16:32:56,273 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.55.0', 'prev_value': None, 'change': True}
2022-09-24 16:32:56,273 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.55.0 (config_version=5, BCP v1.1, Requires MPF v0.55.0-dev.49)', 'prev_value': None, 'change': True}
2022-09-24 16:32:56,275 : INFO : ball_device.bd_trough : State: idle
2022-09-24 16:32:56,286 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2022-09-24 16:32:56,287 : INFO : ball_device.bd_plunger : State: idle
2022-09-24 16:32:56,288 : INFO : ball_device.bd_vukmid : BCH: Initial count: 0
2022-09-24 16:32:56,288 : INFO : ball_device.bd_vukmid : State: idle
2022-09-24 16:32:56,289 : INFO : ball_device.bd_vuktop : BCH: Initial count: 0
2022-09-24 16:32:56,289 : INFO : ball_device.bd_vuktop : State: idle
2022-09-24 16:32:56,367 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2022-09-24 16:32:56,373 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe... your step?')>)
handle: <Handle EventManager._queue_task_done(<Task finishe... your step?')>)>
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\events.py", line 728, in _queue_task_done
    future.result()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\show_controller.py", line 52, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\assets\show.py", line 125, in load
    self._show_validation_error("Show {} does not appear to be a valid show "
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_light_show" >> Show attract_light_show does not appear to be a valid show config. It should be a list of steps. Did you forget the hyphen at the start of your step? Context: attract_light_show Error Code: CFE-show-1 (https://docs.missionpinball.org/en/0.55/logs/CFE-show-1.html)
2022-09-24 16:32:56,432 : INFO : Machine : Starting the main run loop.
2022-09-24 16:32:56,433 : INFO : Machine : Shutting down...
2022-09-24 16:32:56,437 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2022-09-24 16:32:56,440 : ERROR : OPP : Stop called on serial connection COM10
2022-09-24 16:32:56,441 : ERROR : OPP : Stop called on serial connection COM11
2022-09-24 16:32:56,441 : ERROR : OPP : Stop called on serial connection COM7
2022-09-24 16:32:56,445 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\events.py", line 728, in _queue_task_done
    future.result()
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\core\show_controller.py", line 52, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\assets\show.py", line 125, in load
    self._show_validation_error("Show {} does not appear to be a valid show "
  File "C:\Users\dorus\AppData\Local\Programs\Python\Python38\lib\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_light_show" >> Show attract_light_show does not appear to be a valid show config. It should be a list of steps. Did you forget the hyphen at the start of your step? Context: attract_light_show Error Code: CFE-show-1 (https://docs.missionpinball.org/en/0.55/logs/CFE-show-1.html)
2022-09-24 16:32:56,582 : INFO : crash_reporter : Will not report crash as "report_crashes" mode is "never"
2022-09-24 16:32:56,582 : INFO : root : MPF run loop ended.
